FROM postgres:16

ENV POSTGRES_USER=notAdmin3287111
ENV POSTGRES_PASSWORD=KamxnJAnmxiiiiUIUUU
ENV POSTGRES_DB=hackaton_hackaton

EXPOSE 5432

# Default command to run when starting the container
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]