version: "3.8"

services:
  api:
    ports:
      - "8000:8000"
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app/src/
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackaton
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
