version: "3.8"

services:
  api:
    ports:
      - "8000:8000"
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app/src/
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackaton
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/fullchain.pem:/etc/fullchain.pem
      - ./nginx/certs/privkey.pem:/etc/privkey.pem
    depends_on:
      - api

  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}

volumes:
  postgres_data:
