"""added index to unom

Revision ID: 5c4b1d3dfe13
Revises: adef5a4367f2
Create Date: 2024-06-16 17:42:46.193283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4b1d3dfe13'
down_revision = 'adef5a4367f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_public_address_register_of_real_estate_objects_unom'), 'address_register_of_real_estate_objects', ['unom'], unique=False, schema='public')
    op.create_index(op.f('ix_public_addresses_unom'), 'addresses', ['unom'], unique=False, schema='public')
    op.create_index(op.f('ix_public_predictions_unom'), 'predictions', ['unom'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_predictions_unom'), table_name='predictions', schema='public')
    op.drop_index(op.f('ix_public_addresses_unom'), table_name='addresses', schema='public')
    op.drop_index(op.f('ix_public_address_register_of_real_estate_objects_unom'), table_name='address_register_of_real_estate_objects', schema='public')
    # ### end Alembic commands ###
