"""reactions model

Revision ID: a94ca5aae634
Revises: 5c4b1d3dfe13
Create Date: 2024-06-22 17:46:57.294455

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a94ca5aae634'
down_revision = '5c4b1d3dfe13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
                    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('tp_number', sa.String(), nullable=True),
                    sa.Column('address_tp', sa.String(), nullable=True),
                    sa.Column('heat_supply_source', sa.String(), nullable=True),
                    sa.Column('short_address', sa.String(), nullable=True),
                    sa.Column('unom', sa.BIGINT(), nullable=True),
                    sa.Column('ods_number', sa.String(), nullable=True),
                    sa.Column('ods_address', sa.String(), nullable=True),
                    sa.Column('consumer', sa.String(), nullable=True),
                    sa.Column('geodata_y', sa.String(), nullable=True),
                    sa.Column('geodata_center_y', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='public'
                    )
    op.create_index(op.f('ix_public_reactions_id'), 'reactions', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unloading_odpu_heating', 'id_uu',
                    existing_type=sa.BIGINT(),
                    nullable=False)
    op.drop_index(op.f('ix_public_reactions_id'), table_name='reactions', schema='public')
    op.drop_table('reactions', schema='public')
    # ### end Alembic commands ###
