"""added dataFloat table

Revision ID: c453fe1473fc
Revises: 6397e3215a9e
Create Date: 2024-05-13 11:15:05.542963

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c453fe1473fc"
down_revision = "6397e3215a9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datafloat",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("param_id", sa.BIGINT(), nullable=False),
        sa.Column("borehole_id", sa.BIGINT(), nullable=False),
        sa.Column("source_time", sa.DateTime(), nullable=False),
        sa.Column("server_time", sa.DateTime(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("source_id", sa.BIGINT(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "modify_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("datafloat", schema="main")
    # ### end Alembic commands ###
