"""added others models

Revision ID: 72e59557164d
Revises: b03e307b544e
Create Date: 2024-06-11 23:28:26.744152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e59557164d'
down_revision = 'b03e307b544e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_register_of_real_estate_objects',
    sa.Column('global_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('obj_type', sa.String(), nullable=False),
    sa.Column('OnTerritoryOfMoscow', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('unom', sa.BIGINT(), nullable=False),
    sa.Column('P1', sa.String(), nullable=True),
    sa.Column('P3', sa.String(), nullable=True),
    sa.Column('P4', sa.String(), nullable=True),
    sa.Column('P5', sa.String(), nullable=True),
    sa.Column('P6', sa.String(), nullable=True),
    sa.Column('P7', sa.String(), nullable=True),
    sa.Column('P90', sa.String(), nullable=True),
    sa.Column('simple_address', sa.String(), nullable=True),
    sa.Column('P91', sa.String(), nullable=True),
    sa.Column('l1_type', sa.String(), nullable=True),
    sa.Column('l1_value', sa.String(), nullable=True),
    sa.Column('l2_type', sa.String(), nullable=True),
    sa.Column('p0', sa.String(), nullable=True),
    sa.Column('l2_value', sa.String(), nullable=True),
    sa.Column('l3_type', sa.String(), nullable=True),
    sa.Column('l3_value', sa.String(), nullable=True),
    sa.Column('l4_type', sa.String(), nullable=True),
    sa.Column('l5_type', sa.String(), nullable=True),
    sa.Column('adm_area', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('nreg', sa.String(), nullable=True),
    sa.Column('dreg', sa.String(), nullable=True),
    sa.Column('n_fias', sa.String(), nullable=True),
    sa.Column('d_fias', sa.String(), nullable=True),
    sa.Column('kad_n', sa.String(), nullable=True),
    sa.Column('kad_zu', sa.String(), nullable=True),
    sa.Column('kladr', sa.String(), nullable=True),
    sa.Column('tdoc', sa.String(), nullable=True),
    sa.Column('ndoc', sa.String(), nullable=True),
    sa.Column('ddoc', sa.String(), nullable=True),
    sa.Column('adr_type', sa.String(), nullable=True),
    sa.Column('vid', sa.String(), nullable=True),
    sa.Column('sostad', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('geodata', sa.String(), nullable=True),
    sa.Column('geodata_center', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('global_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_address_register_of_real_estate_objects_global_id'), 'address_register_of_real_estate_objects', ['global_id'], unique=False, schema='public')
    op.create_table('economic_characteristics_houses',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('unom', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('col_758', sa.BIGINT(), nullable=True),
    sa.Column('col_759', sa.BIGINT(), nullable=True),
    sa.Column('col_760', sa.BIGINT(), nullable=True),
    sa.Column('col_761', sa.BIGINT(), nullable=True),
    sa.Column('col_762', sa.Float(), nullable=True),
    sa.Column('col_763', sa.Float(), nullable=True),
    sa.Column('col_764', sa.Float(), nullable=True),
    sa.Column('col_766', sa.BIGINT(), nullable=True),
    sa.Column('col_769', sa.BIGINT(), nullable=True),
    sa.Column('col_770', sa.BIGINT(), nullable=True),
    sa.Column('col_771', sa.BIGINT(), nullable=True),
    sa.Column('col_772', sa.BIGINT(), nullable=True),
    sa.Column('col_775', sa.BIGINT(), nullable=True),
    sa.Column('col_781', sa.BIGINT(), nullable=True),
    sa.Column('col_1945_del', sa.BIGINT(), nullable=True),
    sa.Column('col_2463', sa.BIGINT(), nullable=True),
    sa.Column('col_3163', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_economic_characteristics_houses_id'), 'economic_characteristics_houses', ['id'], unique=False, schema='public')
    op.create_table('social_facilities_efficiency_energies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('count_buildings', sa.BIGINT(), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('heated_area', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('employees_average_number', sa.BIGINT(), nullable=True),
    sa.Column('building_type', sa.String(), nullable=True),
    sa.Column('energy_efficiency_class', sa.String(), nullable=True),
    sa.Column('floors_count', sa.BIGINT(), nullable=True),
    sa.Column('elevators_number', sa.BIGINT(), nullable=True),
    sa.Column('building_actual_depreciation', sa.BIGINT(), nullable=True),
    sa.Column('entrance_count', sa.BIGINT(), nullable=True),
    sa.Column('building_start_year', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_social_facilities_efficiency_energies_id'), 'social_facilities_efficiency_energies', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_social_facilities_efficiency_energies_id'), table_name='social_facilities_efficiency_energies', schema='public')
    op.drop_table('social_facilities_efficiency_energies', schema='public')
    op.drop_index(op.f('ix_public_economic_characteristics_houses_id'), table_name='economic_characteristics_houses', schema='public')
    op.drop_table('economic_characteristics_houses', schema='public')
    op.drop_index(op.f('ix_public_address_register_of_real_estate_objects_global_id'), table_name='address_register_of_real_estate_objects', schema='public')
    op.drop_table('address_register_of_real_estate_objects', schema='public')
    # ### end Alembic commands ###
