"""models for units

Revision ID: c024b5c03586
Revises: 1433b1db404d
Create Date: 2024-06-03 14:12:39.947762

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c024b5c03586"
down_revision = "1433b1db404d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit_groups",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )
    op.create_table(
        "unit_models",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )
    op.create_table(
        "unit_names",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )
    op.create_table(
        "machines",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("unit_name", sa.Uuid(), nullable=False),
        sa.Column("unit_group", sa.Uuid(), nullable=False),
        sa.Column("unit_model", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_group"],
            ["main.unit_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_model"],
            ["main.unit_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_name"],
            ["main.unit_names.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )
    op.create_table(
        "machine_images",
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["main.files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["main.machines.id"],
        ),
        sa.PrimaryKeyConstraint("machine_id", "image_id"),
        schema="main",
    )
    op.drop_index("datafloat_param_id_idx", table_name="datafloat", schema="main")
    op.create_index(
        "idx_col345",
        "datafloat",
        ["param_id", "borehole_id", "source_time"],
        unique=False,
        schema="main",
    )
    op.create_foreign_key(
        None,
        "params",
        "uom",
        ["uom_id"],
        ["id"],
        source_schema="main",
        referent_schema="main",
    )
    op.drop_column("params", "modify_at", schema="main")
    op.drop_column("params", "created_at", schema="main")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "params",
        sa.Column(
            "created_at",
            sa.DATE(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        schema="main",
    )
    op.add_column(
        "params",
        sa.Column(
            "modify_at",
            sa.DATE(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        schema="main",
    )
    op.drop_constraint(None, "params", schema="main", type_="foreignkey")
    op.drop_index("idx_col345", table_name="datafloat", schema="main")
    op.create_index(
        "datafloat_param_id_idx",
        "datafloat",
        [
            sa.text("param_id DESC"),
            sa.text("borehole_id DESC"),
            sa.text("source_time DESC"),
        ],
        unique=False,
        schema="main",
    )
    op.drop_table("machine_images", schema="main")
    op.drop_table("machines", schema="main")
    op.drop_table("unit_names", schema="main")
    op.drop_table("unit_models", schema="main")
    op.drop_table("unit_groups", schema="main")
    # ### end Alembic commands ###
